### ISSUE TITLE
An issue with the installation

### ISSUE THREAD

**Issue by Saberfish** [QCOL-LU/MaxKcut#1]
I download the zip package and unzip it. Then I execute :
python setup.py install
pip3 install qiskit numpy scipy matplotlib networkx
conda install -c gurobi gurobi
conda install -c mosek mosek

And then I try to import the max_k_cut by "from max_k_cut import * ", but it shows "ModuleNotFoundError: No module named 'max_k_cut' "
But I check the module by pip list, the max-k-cut version 0.0.1 is already installed.
Any suggestions from you would be greatly appreciated！

**Comment by Saberfish** [comment]
PS：When I execute "python setup.py install",it shows:
warning: install_lib: 'build\lib' does not exist -- no Python modules to install
When I execute "pip3 install MaxKcut", it shows:
ERROR: Could not find a version that satisfies the requirement MaxKcut (from versions: none)
ERROR: No matching distribution found for MaxKcut

**Comment by fakhimi** [comment]
Thanks for letting us know. We will check that.

**Comment by makoto-yamashita** [comment]
I am encountering the same error.

pip3 install MaxKcut
ERROR: Could not find a version that satisfies the requirement MaxKcut (from versions: none)

Here is what I am trying.
$ python -m venv .venv
$ source .venv/bin/activate
$ git clone https://github.com/QCOL-LU/MaxKcut.git
$ pip3 install MaxKcut

Thank you very much for developing an interesting package.

**Comment by QCOL-LU** [comment]
I have updated the installation instruction. Please let me know if you still have the same problem.

**Comment by makoto-yamashita** [comment]
Thank you very much for your quick reply. I have tried the new instruction, but python cannot find the module yet...

$ python3.9 -m venv .venv
$ source .venv/bin/activate
$ git clone https://github.com/QCOL-LU/MaxKcut.git
$ pip3.9 install -e MaxKcut/max_k_cut
    Preparing metadata (setup.py) ... done
  Installing collected packages: max-k-cut
    Running setup.py develop for max-k-cut
  Successfully installed max-k-cut-0.0.2
$ python3.9
Python 3.9.10 
>>> import max_k_cut
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'max_k_cut'

However, pip can list the package correctly.
$ pip3.9 list | grep max
max-k-cut         0.0.2

**Comment by QCOL-LU** [comment]
Make sure that you are in directory `MaxKcut` otherwise, you may need to use a similar approach as follows
```
import sys

sys.path.insert(1, 'max_k_cut directory address')
```

**Comment by Saberfish** [comment]
Thank you for your reply! That really works for me!

**Comment by makoto-yamashita** [comment]
Thank you very much for the reply. It works for me, too.

I have not installed gurobi, so I am modifying
  problem.Params.Method  = "BQO"
to
  problem.Params.Method  = "QUBO"
and it works well.

**Comment by d6o0** [comment]
Hello, I want to know the version of qiskit you used.
There is an error saying : No module named 'qiskit.circuit.library.standard_gates'
Its seems that standard_gates module is removed when version update.
