### ISSUE TITLE
How to apply the algorithm in the weighted graph？

### ISSUE THREAD

**Issue by Saberfish** [QCOL-LU/MaxKcut#2]
If I have a weighted graph, how to color the nodes of a graph with at most k colors such that the sum of weight of edges with distinct colored endpoints is maximized?
Thank you for any reply！

**Comment by fakhimi** [comment]
That is the max k-cut problem. You can check the literature to see how to solve it. You can also check [our paper](https://engineering.lehigh.edu/sites/engineering.lehigh.edu/files/_DEPARTMENTS/ise/pdf/tech-papers/21/21T_007a.pdf).
